### PR TITLE
[release-4.14][manual] improve support to coexist with standard scheduler

### PR DESCRIPTION
**Pull request by ffromani**
manual backport of #952  to stable branch 4.15.

Add API field to configure the resync strategy.

We used to configure the cache resync code to:
- react to any foreign pod (= pod not scheduled by this scheduler)
- consider all the pods when computing the expected node state

But thinking about it, only pods whose containers require exclusive resources are relevant to the node state, because only exclusive resources can have NUMA affinity.

We retroactively dub this configuration "aggressive" because it causes recomputation when any change is detected, even unnecessary ones.

Recomputing the state often creates more work on the scheduler process, but most notably slows down the scheduling because we need to wait more for resyncs, being the current state invalidated (because of aggressive detection).

To improve in both areas (resource consumption but most notably scheduling latency) we add a new mode, called "relaxed" on which we leverage the scheduler options to react and consider only pods whose containers require exclusive resources.

The new "relaxed" mode is enabled by default, and the old behavior can be re-enabled with a configuration option.

release-4.14 specific notes: please see commit fa5ba29949a7120c33c80b5d0b3c2caf1140036d
release-4.14 specific notes: e2e tests not backported yet

### CODE REVIEW

**Comment by shajmakh** [comment]
lgtm but let's wait for the ci to pass

**Comment by ffromani** [comment]
Ci failures look legit. I'll setup a repro.

**Comment by ffromani** [comment]
needs to be rebased on top of #846 once the latter merges

**Comment by ffromani** [comment]
#846 dropped, changed accordingly. We should now be good to go

**Comment by Tal-or** [comment]
/lgtm
trivial backport

**Pull request merged**
