### PR TITLE
[manual][release-4.12] add support for scheduler cache using the reserve plugin

### PR DESCRIPTION
**Pull request by ffromani**
Enable the scheduler-side cache using the reserve plugin. The functionality is controlled solely by a new optional scheduler spec parameter, `CacheResyncSeconds`. If present and > 0, it will enable the functionality.
Default is disabled for backward compatibility.

Manual backport of https://github.com/openshift-kni/numaresources-operator/pull/443

### CODE REVIEW

**Comment by ffromani** [comment]
/hold
let's check the backporting timeline before

**Comment by ffromani** [comment]
/hold cancel
if the change is not backward compatible as it should, the sooner we know the better

**Comment by ffromani** [comment]
/retest
failed for a different reason (installplan failed)

**Comment by ffromani** [comment]
So:

1. we will need a manual, albeit trivial, rebase because we backported PRs in a different order than the one was used for main branch. This is partly my (ffromani's) fault, partly a byproduct of circumstances. We will revisit the backport process and improve where possible
2. the RTE errors we are experiencing are IMO red herrings. The core issue is the scheduler plugin was NOT backported yet. But the operator always sends the `cacheResyncPeriod` param even when 0 (to allow the enabled->disabled transition in the easiest way). So the scheduler plugin is likely to fail to startup (not demonstrated but all the hints point there) which cause cascading failures later on
3. it would be nice to investigate further why the `exporter` binary is missing and if we are silently skipping tests, but this, albeit important, is a separate task.

**Comment by ffromani** [comment]
reopen because the reserve plugin/cache support was backported to scheduler-plugin 4.12, and new container image have been built by automation

**Comment by ffromani** [comment]
/hold cancel
all concerns addressed (there could be lower-priority followups later)

**Review by swatisehgal — APPROVED** [review]
/lgtm
/approve

NIT: I would add reference to the original [PR](https://github.com/openshift-kni/numaresources-operator/pull/443) being backported in the PR description.

**Comment by ffromani** [comment]
> /lgtm /approve
> 
> NIT: I would add reference to the original [PR](https://github.com/openshift-kni/numaresources-operator/pull/443) being backported in the PR description.

good point, fixed

**Pull request merged**
