### PR TITLE
[release-4.17][manual] NO-JIRA: controller:annotation: introduce pause annotation

### PR DESCRIPTION
**Pull request by Tal-or**
Manual backport of #1102

### CODE REVIEW

**Comment by Tal-or** [comment]
@ffromani 
Do we need a bug here?

**Comment by ffromani** [comment]
> @ffromani Do we need a bug here?

not if we can help it

**Review by ffromani — COMMENTED** [review]
/approve
/lgtm

**Comment by Tal-or** [comment]
bahhh not again
```
 ✗ [Medium] Improper Neutralization of Directives in Statically Saved Code
   ID: 0079acea-103f-4c9a-990a-b0468d867361 
   Path: vendor/github.com/spf13/cobra/command.go, line 915 
   Info: Unsanitized input from a CLI argument flows into text.template.New, where it is used to construct a template that gets rendered. This may result in a Server-Side Template Injection vulnerability.
```

**Pull request merged**
