### PR TITLE
serial: add new tests with device resources

### PR DESCRIPTION
**Pull request by shajmakh**
Automate new tests involving device resources while the test pod is non-guaranteed.
Test cases id:
54022,54023,54025,55429,55430,55431

### CODE REVIEW

**Comment by shajmakh** [comment]
1. split sched.Status fix 
2. add new TC + update ids for the different scopes cases
3. remove unneeded changes

**Comment by shajmakh** [comment]
sched.Status fix: https://github.com/openshift-kni/numaresources-operator/pull/459

**Review by swatisehgal — APPROVED** [review]
Thanks for your work on automating the tests! It is really appreciated :) 

/lgtm

**Review by fromanirh — APPROVED** [review]
/lgtm
nice work!

**Comment by fromanirh** [comment]
/retest
download/build failures (never a boring day!)

**Pull request merged**
