### PR TITLE
[DNM] Quick fix to check if selinux policy change is compatible with 4.11

### PR DESCRIPTION
**Pull request by swatisehgal**
Signed-off-by: Swati Sehgal <swsehgal@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
/hold
agreed offline: let's check if the fix is fixing before we finalize the proper change

**Comment by fromanirh** [comment]
the failure is surprising. Cherry-picked on top of https://github.com/openshift-kni/numaresources-operator/pull/324 to get better logs

**Comment by swatisehgal** [comment]
> the failure is surprising. Cherry-picked on top of #324 to get better logs

Yeah, surprising indeed! Thanks for cherry-picking. Let's see what is going on.

**Comment by fromanirh** [comment]
you may want to rebase on top of the main branch to make sure you have all the (unrelated) fixes in your lane runs

**Comment by swatisehgal** [comment]
> you may want to rebase on top of the main branch to make sure you have all the (unrelated) fixes in your lane runs

Ah yeah! Thanks, doing that.

**Comment by fromanirh** [comment]
```
level=error
level=error msg=Error: error reading Route Table (rtb-0c1ea9e3e4f8c5e8f): couldn't find resource 
```

**Comment by swatisehgal** [comment]
/close

We have already validated in other PR(s) that this change resolves the issues in the Ci.

**Pull request closed without merging**
