### PR TITLE
numaresourcescheduler: update KubeSchedulerConfiguration api version

### PR DESCRIPTION
**Pull request by Tal-or**
Moving forward with u/s, we're updating KubeSchedulerConfiguration API version from betav1 -> betav2.
This will also require the controller to deploy the 4.11 release of the scheduler-plugins which align with the KubeSchedulerConfiguration betav2 API version.

The current E2E tests that we have, should already cover this change. IOW if something isn't align properly the tests will failed.

Signed-off-by: Talor Itzhak <titzhak@redhat.com>

### CODE REVIEW

**Comment by fromanirh** [comment]
/lgtm
```
 IOW if something isn't align properly the tests will failed.
```
(english) nit: "the tests will fail"
the change looks correct to me.

**Comment by Tal-or** [comment]
>         FailedSchedulerSync: no kind "KubeSchedulerConfiguration" is registered for version "kubescheduler.config.k8s.io/v1beta2" in scheme "k8s.io/client-go/kubernetes/scheme/register.go:72"

Right now we're using scheduler-plugins [version v0.19.9](https://github.com/openshift-kni/numaresources-operator/blob/main/go.mod#L144)
It looks like we'll need to bump the deployer and do some refactoring in order to use the latest.

**Comment by Tal-or** [comment]
/hold
Depends on https://github.com/k8stopologyawareschedwg/deployer/pull/92

**Comment by Tal-or** [comment]
Depends on https://github.com/k8stopologyawareschedwg/deployer/pull/96

**Comment by Tal-or** [comment]
/retest 
infra issue
```Link to step on registry info site: https://steps.ci.openshift.org/reference/gather-aws-console
Link to job on registry info site: https://steps.ci.openshift.org/job?org=openshift-kni&repo=numaresources-operator&branch=main&test=ci-e2e, "ci-e2e" pod "ci-e2e-gather-must-gather" failed: the pod ci-op-jsqzbwit/ci-e2e-gather-must-gather failed after 7s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 1, reason Error
---
Running must-gather...
Error running must-gather collection:
    <nil>```

**Review by ffromani — APPROVED** [review]
/lgtm

**Comment by fromanirh** [comment]
the test `"[test_id:48598][tier2] should perform the scheduler deployment and verify the condition is reported as available"` is failing and the failure seems legit. But the test is not giving us enough context to understand what's broken. We should probably revisit it (in another PR ofc).

**Comment by Tal-or** [comment]
> the test `"[test_id:48598][tier2] should perform the scheduler deployment and verify the condition is reported as available"` is failing and the failure seems legit. But the test is not giving us enough context to understand what's broken. We should probably revisit it (in another PR ofc).

Is it one of flaky tests that @shajmakh handles or falling constantly?

**Comment by Tal-or** [comment]
This test failed as well

```  
 [NotificationFile] it should react to pod changes using the smart poller with notification file [It]
    /go/src/github.com/openshift-kni/numaresources-operator/vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go:151
    failed to execute command in namespace openshift-numaresources pod numaresourcesoperator-worker-gdlw6, container resource-topology-exporter: command terminated with exit code 1
              
    Unexpected error:
        <exec.CodeExitError>: {
            Err: <*errors.errorString | 0xc000952050>{
                s: "command terminated with exit code 1",
            },
            Code: 1,
        }
        command terminated with exit code 1
    occurred
    /go/src/github.com/openshift-kni/numaresources-operator/vendor/github.com/k8stopologyawareschedwg/resource-topology-exporter/test/e2e/rte/rte.go:224
```

**Comment by fromanirh** [comment]
maybe consume (a fixed version of) https://github.com/openshift-kni/numaresources-operator/pull/236 to get more insights about why the test is failing

**Comment by fromanirh** [comment]
install lane succeeded, this reinforces my feeling the e2e lane failures are legit

**Comment by fromanirh** [comment]
same error on retries, something's off.

**Comment by Tal-or** [comment]
> same error on retries, something's off.

This is really suspicious. The test that falling runs against RTE component (notification file test) while the changes are only affecting the scheduler part.

**Comment by fromanirh** [comment]
true, that's a flake. But we also have 
```
[It] [test_id:48598][tier2] should perform the scheduler deployment and verify the condition is reported as available 
```
failing like few times in a row

**Comment by Tal-or** [comment]
> true, that's a flake. But we also have
> 
> ```
> [It] [test_id:48598][tier2] should perform the scheduler deployment and verify the condition is reported as available 
> ```
> 
> failing like few times in a row

Let me finish something and I'll dive into the bottom of it

**Comment by Tal-or** [comment]
> looking at the PR test history (https://prow.ci.openshift.org/pr-history/?org=openshift-kni&repo=numaresources-operator&pr=231) it seems unlikely this is a flake. We need to dive deeper here.

This PR intended to solve at least one of the issues https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/105

**Comment by fromanirh** [comment]
awesome! many thanks to @Tal-or for pushing this through, finding many related improvements along the way, and to @cynepco3hahue for the critical insight about https://github.com/openshift/release/pull/27652

**Pull request merged**
