### PR TITLE
manifests: add bundle

### PR DESCRIPTION
**Pull request by mmirecki**
appropriate parameters provided

To generate the files in this commit, the following parameters
were used with the command:
VERSION=4.10.0 IMG=quay.io/fromani/numaresource-operator:latest make bundle

Note that when running the command for the first time or when the
bundle files are removed, the command will ask additional questions,
asking for:

operator name
operator description
provider name
provider url
maintainers
operator keywords

NOTE: no controller binary args are set for now, this will be added in another PR

### CODE REVIEW

**Comment by fromanirh** [comment]
Thanks, almost there. Let's fix the commit message and we should be good. It should read:
```
manifests: add bundle

The bundle files can be generated using "make bundle" with appropriate parameters provided.

To generate the files in this commit, the following parameters
were used with the command:
VERSION=4.10.0 IMG=quay.io/fromani/numaresource-operator:latest make bundle
```

**Comment by mmirecki** [comment]
> Thanks, almost there. Let's fix the commit message and we should be good. It should read:
> 
> ```
> manifests: add bundle
> 
> The bundle files can be generated using "make bundle" with appropriate parameters provided.
> 
> To generate the files in this commit, the following parameters
> were used with the command:
> VERSION=4.10.0 IMG=quay.io/fromani/numaresource-operator:latest make bundle
> ```

fixed

**Comment by fromanirh** [comment]
thanks @mmirecki , looks fine now!

**Pull request merged**
