### PR TITLE
Provide a way to verify generated content via git hook and via our CI

### PR DESCRIPTION
**Pull request by cynepco3hahue**
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>

### CODE REVIEW

**Review by fromanirh — COMMENTED** [review]
please elaborate in the commit message the usecase, meaning on which circumstances this would help? do we plan to add this as part of our CI flows? is this something developers are expected to run before they submit changes? maybe a pre-commit hook? (in the latter cases, how can they know to run this check?)

Besides this, LGTM, a nice and welcome addition.

**Comment by cynepco3hahue** [comment]
> please elaborate in the commit message the usecase, meaning on which circumstances this would help? do we plan to add this as part of our CI flows? is this something developers are expected to run before they submit changes? maybe a pre-commit hook? (in the latter cases, how can they know to run this check?)

I already added it under github actions CI. But totally will elaborate it under the commit message.

**Comment by fromanirh** [comment]
> > please elaborate in the commit message the usecase, meaning on which circumstances this would help? do we plan to add this as part of our CI flows? is this something developers are expected to run before they submit changes? maybe a pre-commit hook? (in the latter cases, how can they know to run this check?)
> 
> I already added it under github actions CI. But totally will elaborate it under the commit message.

ah, right, silly me missed the very first commit. Sorry!

**Comment by cynepco3hahue** [comment]
> ah, right, silly me missed the very first hunk in the commit. Sorry!

Ye, but pre-commit hook is a good idea.

**Comment by cynepco3hahue** [comment]
@fromanirh Update the PR.

**Review by fromanirh — COMMENTED** [review]
/lgtm

**Comment by fromanirh** [comment]
> @fromanirh Update the PR.

thanks! LGTM

**Pull request merged**
