### PR TITLE
rte: deps: update to 0.14

### PR DESCRIPTION
**Pull request by ffromani**
Bump to RTE 0.14.0 and make the necessary API changes.

### CODE REVIEW

**Comment by ffromani** [comment]
/hold

let's branch off before to merge this

**Comment by ffromani** [comment]
/hold cancel

4.14 branch done

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by ffromani** [comment]
backport to 4.14 is still fine, but we should not go older than that

**Pull request merged**
