### PR TITLE
e2e: serial: fix pod generation

### PR DESCRIPTION
**Pull request by fromanirh**
Fix pod naming issues emerged during the fine tuining of the e2e serial suite.
Please check the individual commits for details.

### CODE REVIEW

**Comment by fromanirh** [comment]
/hold
let me have a test run myself

**Comment by fromanirh** [comment]
/retest
```
error updating LB Target Group
```
infra issue

**Comment by fromanirh** [comment]
/hold
running last tests

**Review by Tal-or — COMMENTED** [review]
Sorry for my ignorance, but what does it mean from the PR's comment:
_the hostname can make the pod name exceed the limit_

**Comment by fromanirh** [comment]
> Sorry for my ignorance, but what does it mean from the PR's comment: _the hostname can make the pod name exceed the limit_

Pod name can't be longer than 63 chars. If we construct the name using prefix (`padpod-` in this case) + hostname + extra (zone name like `zone-$NUM`) it becomes quite easy to end up with constructed names longer than 63 chars.
This will cause the apiserver to reject the pod creation right from the start.

**Comment by fromanirh** [comment]
/hold cancel
good enough for now, we will add targeted fixes (if needed) when enabling the tests to scope=pod in future PRs.

**Comment by Tal-or** [comment]
/lgtm
/approve
We'll probably need to do the same for the padder package

**Pull request merged**
