### PR TITLE
api: manifests: add scorecard annotations

### PR DESCRIPTION
**Pull request by fromanirh**
add annotations to make the operator-sdk scorecard check happy.

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
/lgtm
Can we add a scorecard check under the CI to avoid such issue in the future, for sure it is subject for a separate PR.

**Comment by fromanirh** [comment]
> /lgtm Can we add a scorecard check under the CI to avoid such issue in the future, for sure it is subject for a separate PR.

that's a very nice idea: https://github.com/openshift-kni/numaresources-operator/issues/155

**Comment by fromanirh** [comment]
well known flake, for which we don't have a good solution yet

**Pull request merged**
