### PR TITLE
version: bump to 4.15

### PR DESCRIPTION
**Pull request by ffromani**
now that we branched off 4.14 we can move the main branch to 4.15

### CODE REVIEW

**Comment by shajmakh** [comment]
/lgtm
Thanks for the PR, the CI failures look like infra issues, but leaving it for you to have a look

**Comment by ffromani** [comment]
> /lgtm Thanks for the PR, the CI failures look like infra issues, but leaving it for you to have a look

we surely need 4.15 scheduler plugin builds, which are not available because the mirroring job is broken atm: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-image-mirroring-openshift-kni

**Comment by ffromani** [comment]
/retest

we have scheduler-plugin builds now

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Pull request merged**
