### PR TITLE
rte: move kni-specific packages to klog

### PR DESCRIPTION
**Pull request by fromanirh**
it's just ugly to mix `log` and `klog`, and
we have no real reason to be stuck with `log`.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by cynepco3hahue** [comment]
oo yee
/lgtm

**Comment by Tal-or** [comment]
We also have some here https://github.com/openshift-kni/numaresources-operator/blob/main/test/e2e/e2e_suite_test.go#L22

**Comment by fromanirh** [comment]
> We also have some here https://github.com/openshift-kni/numaresources-operator/blob/main/test/e2e/e2e_suite_test.go#L22

thanks, updated

**Pull request merged**
