### PR TITLE
test: e2e: rte: move to dedicated GH actions lane

### PR DESCRIPTION
**Pull request by fromanirh**
Add more troubleshooting logs when finding executables.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by shajmakh** [comment]
/lgtm
thanks!

**Comment by fromanirh** [comment]
```
 level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: error reading Route Table (rtb-06a8dce8668b78857): couldn't find resource 
```
:\

**Pull request merged**
