### PR TITLE
deps: bump RTE and deployer to 0.7.3

### PR DESCRIPTION
**Pull request by shajmakh**
Update RTE and deployer versions to consume the fixes for recognizing new devices.

Signed-off-by: shereenH <shajmakh@redhat.com>

### CODE REVIEW

**Comment by shajmakh** [comment]
cc @fromanirh 
May you have a look please?

**Comment by fromanirh** [comment]
updating deployer LGTM (but let's jump to 0.7.5) but the feature should have been enabled already in https://github.com/openshift-kni/numaresources-operator/pull/408

**Comment by fromanirh** [comment]
@shajmakh I think we addressed this in the other PRs, is this still relevant?

**Comment by shajmakh** [comment]
> @shajmakh I think we addressed this in the other PRs, is this still relevant?

nope, closing it. Thanks!

**Pull request closed without merging**
