### PR TITLE
deps: rte: consume latest changes from u/s

### PR DESCRIPTION
**Pull request by fromanirh**
fetch fix to update tm policy changes in NRT objects.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Review by jlojosnegros — APPROVED** [review]
/ltgm

**Review by marioferh — APPROVED** [review]
/lgtm

**Comment by fromanirh** [comment]
/override ci/prow/ci-e2e 
/override ci/prow/ci-install-e2e
tests passed before

**Pull request merged**
