### PR TITLE
serial: set container images via the function

### PR DESCRIPTION
**Pull request by shajmakh**
Some CI environments are disconnected and cannot pull images outside the local host image registry. A way to overcome this unreachability is via setting one of the environment variables: E2E_NROP_URL_PAUSE_IMAGE, E2E_PAUSE_IMAGE_URL to have an image that is reachable by the local host. Thus tests should not use the value of PauseImage directly but via the function that fetches the desired image to use for the tests which is images.GetPauseImage().

Signed-off-by: shereenH <shajmakh@redhat.com>

### CODE REVIEW

**Comment by shajmakh** [comment]
/hold 
not tested due to env deployment complications.

**Comment by shajmakh** [comment]
might need to add env var for pause command to match the image passed by those env vars:E2E_NROP_URL_PAUSE_IMAGE, E2E_PAUSE_IMAGE_URL 
will test and decide once I have an appropriate cluster.

**Review by fromanirh — APPROVED** [review]
/lgtm
/approve
thanks for this cleanup!

**Comment by fromanirh** [comment]
related improvement: https://github.com/openshift-kni/numaresources-operator/pull/418

**Pull request merged**
