### PR TITLE
e2e: fix resource accounting tests

### PR DESCRIPTION
**Pull request by fromanirh**
grab bag of fixes for the resource accounting tests

### CODE REVIEW

**Comment by fromanirh** [comment]
/hold
@shajmakh PTAL

**Comment by swatisehgal** [comment]
/lgtm

Thanks for the PR.

**Comment by fromanirh** [comment]
the e2e lane failed at deprovisioning stage (!!!), the tests themselves are green.

**Comment by shajmakh** [comment]
/lgtm
thanks for the fixes!

**Pull request merged**
