### PR TITLE
[release-4.15] manual cherry-pick of 900,910,912

### PR DESCRIPTION
**Pull request by shajmakh**
manual cherry pick of:
https://github.com/openshift-kni/numaresources-operator/pull/905/commits/dfd0feca7e0eebae2731cc29816e5d23a1b0ce2f
#910 
#900

### CODE REVIEW

**Comment by shajmakh** [comment]
/hold 
for #912 to merge first

**Comment by ffromani** [comment]
/approve
/lgtm

thanks for the manual backport!

**Pull request merged**
