### PR TITLE
chore: lint: fixes 20231107

### PR DESCRIPTION
**Pull request by ffromani**
partial address of lint warnings after we enabled in the test subtree in #758

### CODE REVIEW

**Review by swatisehgal — COMMENTED** [review]
We have a few more lint failures in the last two commits because of which CI linter is failing but other than that the PR looks straightforward.

**Comment by ffromani** [comment]
> We have a few more lint failures in the last two commits because of which CI linter is failing but other than that the PR looks straightforward.

yes, the missing bits are nontrivial and will be addressed in separate PRs.

**Review by jlojosnegros — COMMENTED** [review]
/lgtm

**Comment by ffromani** [comment]
> > We have a few more lint failures in the last two commits because of which CI linter is failing but other than that the PR looks straightforward.
> 
> yes, the missing bits are nontrivial and will be addressed in separate PRs.

like: https://github.com/openshift-kni/numaresources-operator/pull/766

**Pull request merged**
