### PR TITLE
doc: examples: use ctrreschk releases

### PR DESCRIPTION
**Pull request by ffromani**
let's use releases instead of snapshots, and
the first available release is v0.0.3.

### CODE REVIEW

**Comment by Tal-or** [comment]
> /test ci-install-e2e

I think there's a problem with the operator sdk cli image I recently added.
Although it surprising, because the other lanes are using the same image.

You welcome to open a thread on the test platform channel, I'll have a deeper look on Sunday

**Comment by ffromani** [comment]
> > /test ci-install-e2e
> 
> I think there's a problem with the operator sdk cli image I recently added. Although it surprising, because the other lanes are using the same image.
> 
> You are welcome to open a thread on the test platform channel, I'll have a deeper look on Sunday

thanks for catching!

**Comment by Tal-or** [comment]
> > > /test ci-install-e2e
> > 
> > 
> > I think there's a problem with the operator sdk cli image I recently added. Although it surprising, because the other lanes are using the same image.
> > You are welcome to open a thread on the test platform channel, I'll have a deeper look on Sunday
> 
> thanks for catching!
> 
> the retry is already past that point though: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift-kni_numaresources-operator/1009/pull-ci-openshift-kni-numaresources-operator-main-ci-install-e2e/1834477655957704704

Then it was just a glitch with image and that explains why the other lanes passed.

**Pull request merged**
