### PR TITLE
e2e: untie k8s e2e framework from rte test suite

### PR DESCRIPTION
**Pull request by Tal-or**
A continuation of the work done at https://github.com/k8stopologyawareschedwg/resource-topology-exporter
in order to remove the dependencies in the k8s e2e framework.

The framework client replaced with the local clients provided by the `clients` package.

### CODE REVIEW

**Comment by ffromani** [comment]
> /retest

Unfortunatelty a rebase is needed more than retests

**Comment by Tal-or** [comment]
> > /retest
> 
> Unfortunatelty a rebase is needed more than retests

The bot hasn't complain about rebase

**Comment by Tal-or** [comment]
depends on: https://github.com/openshift-kni/numaresources-operator/pull/680

**Comment by Tal-or** [comment]
depends on https://github.com/k8stopologyawareschedwg/resource-topology-exporter/pull/200

**Comment by ffromani** [comment]
please rebase again, thanks!

**Comment by ffromani** [comment]
backported in #770 (with manual action and PR reshuffling)

**Pull request merged**
