### PR TITLE
e2e: install: skip broken test

### PR DESCRIPTION
**Pull request by ffromani**
We need more time and investment to fix this test, so let's
skip it meanwhile.

Signed-off-by: Francesco Romani <fromani@redhat.com>

### CODE REVIEW

**Comment by swatisehgal** [comment]
Given that we have an open PR investigating and fixing the issue, I think it is okay to skip for now.

/lgtm

**Comment by fromanirh** [comment]
there is another investigation ongoing carried by @Tal-or . Let's wait a bit to see where this is heading and we will decide

**Comment by fromanirh** [comment]
/hold cancel
we decided offline to move forward with the backlog while the proper investigation is ongoing

**Pull request merged**
