### PR TITLE
RTE: enable refresh-node-resources feature

### PR DESCRIPTION
**Pull request by Tal-or**
This PR contains all the necessary changes for the `refresh-node-resources` feature enablement.
More details in the commits themselves.

### CODE REVIEW

**Review by ffromani — APPROVED** [review]
/lgtm
good work here, thanks.

**Comment by fromanirh** [comment]
/hold
letting other reviewers chime in

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by swatisehgal** [comment]
/unhold

I think we can go ahead and merge this.

**Comment by fromanirh** [comment]
> /unhold
> 
> I think we can go ahead and merge this.

totally!

**Comment by Tal-or** [comment]
Thanks folks

**Pull request merged**
