### PR TITLE
operator: rte: default inforefreshmode=periodic

### PR DESCRIPTION
**Pull request by ffromani**
We documented that the default InfoRefreshMode value should be "Periodic", not "PeriodicAndEvents", so let's fix the code accordingly.

### CODE REVIEW

**Review by swatisehgal — APPROVED** [review]
/lgtm

**Comment by ffromani** [comment]
infra issues so far

**Comment by shajmakh** [comment]
@ffromani do we need this cherry-picked to release-4.13?

**Comment by ffromani** [comment]
yes and also to 4.12. But this will require full validation (= full run of the serial suite) so let's plan accordingly.

**Pull request merged**
