### PR TITLE
deps: bump to k8s 1.26, RTE 0.12.0

### PR DESCRIPTION
**Pull request by ffromani**
Simple but quite massive deps bump, with minimal necessary codebase changes to adapt to new APIs.

### CODE REVIEW

**Comment by Tal-or** [comment]
/lgtm
/approve
We need to take into account that we cannot bump to 1.27 because we depend on runtime-controller which didn't
bump to 1.27 yet: https://github.com/operator-framework/operator-sdk/issues/6381

**Comment by ffromani** [comment]
> /lgtm /approve We need to take into account that we cannot bump to 1.27 because we depend on runtime-controller which didn't bump to 1.27 yet: [operator-framework/operator-sdk#6381](https://github.com/operator-framework/operator-sdk/issues/6381)

GREAT point, thanks for raising. I think we can stick on 1.26.z for the time being and we do NOT need to jump on 1.27 shortly.

**Comment by Tal-or** [comment]
Not sure whether it's an infra issue or real one:
```
ClusterServiceVersion numaresources-operator.v4.14.999-snapshot was created but never became ready
Dumping ClusterServiceVersion numaresources-operator.v4.14.999-snapshot as /logs/artifacts/csv-numaresources-operator.v4.14.999-snapshot.yaml
  ClusterServiceVersion numaresources-operator.v4.14.999-snapshot status phase: Failed
  ClusterServiceVersion numaresources-operator.v4.14.999-snapshot status message: install failed: deployment numaresources-controller-manager not ready before timeout: deployment "numaresources-controller-manager" exceeded its progress deadline
  ClusterServiceVersion numaresources-operator.v4.14.999-snapshot status reason: InstallCheckFailed
Dumping all installPlans in namespace numaresources-operator as /logs/artifacts/installPlans.yaml
```

**Comment by ffromani** [comment]
> Not sure whether it's an infra issue or real one:
> 
> ```
> ClusterServiceVersion numaresources-operator.v4.14.999-snapshot was created but never became ready
> Dumping ClusterServiceVersion numaresources-operator.v4.14.999-snapshot as /logs/artifacts/csv-numaresources-operator.v4.14.999-snapshot.yaml
>   ClusterServiceVersion numaresources-operator.v4.14.999-snapshot status phase: Failed
>   ClusterServiceVersion numaresources-operator.v4.14.999-snapshot status message: install failed: deployment numaresources-controller-manager not ready before timeout: deployment "numaresources-controller-manager" exceeded its progress deadline
>   ClusterServiceVersion numaresources-operator.v4.14.999-snapshot status reason: InstallCheckFailed
> Dumping all installPlans in namespace numaresources-operator as /logs/artifacts/installPlans.yaml
> ```

I'm hitting the very same issue in NROP (https://github.com/openshift-kni/numaresources-operator/pull/663) this is very very hardly a coincidence. It seems something broke in infra.

**Comment by ffromani** [comment]
> Not sure whether it's an infra issue or real one:
> 
> ```
> ClusterServiceVersion numaresources-operator.v4.14.999-snapshot was created but never became ready
> Dumping ClusterServiceVersion numaresources-operator.v4.14.999-snapshot as /logs/artifacts/csv-numaresources-operator.v4.14.999-snapshot.yaml
>   ClusterServiceVersion numaresources-operator.v4.14.999-snapshot status phase: Failed
>   ClusterServiceVersion numaresources-operator.v4.14.999-snapshot status message: install failed: deployment numaresources-controller-manager not ready before timeout: deployment "numaresources-controller-manager" exceeded its progress deadline
>   ClusterServiceVersion numaresources-operator.v4.14.999-snapshot status reason: InstallCheckFailed
> Dumping all installPlans in namespace numaresources-operator as /logs/artifacts/installPlans.yaml
> ```

let's crosscheck with #667

**Comment by ffromani** [comment]
turns out the root cause is requires: https://github.com/openshift/release/pull/41614 (arguably it WAS infra issue... but the infra issue was on us!)

**Pull request merged**
