### PR TITLE
rte: consume dep v0.20.z

### PR DESCRIPTION
**Pull request by ffromani**
Trimmed down version of https://github.com/openshift-kni/numaresources-operator/pull/1090
We consume the RTE v0.20.z but for the time being we keep using command line flags to control RTE, postponing the move to config files.

### CODE REVIEW

**Comment by Tal-or** [comment]
MCP timeouts again?

**Comment by ffromani** [comment]
> MCP timeouts again?

from what I gathered MCP was still updating after ~40m after we posted our objects, which seems hardly this PR's fault. But let's see.

**Comment by ffromani** [comment]
inspection of the CI cluster strongly suggests MCO/infra issue. But I want to do our due diligence.

**Comment by Tal-or** [comment]
@ffromani #1097

**Pull request merged**
